language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  - ARCH=x86_64
  - ARCH=i686
addons:
  apt:
    packages:
      - gcc-multilib
cache: cargo
sudo: false
script: |
  curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
  cargo test && cargo bench
  rustc -vV | grep -q nightly && cargo test --features simd-accel && cargo bench --features simd-accel &&\
  cargo test --features avx-accel && cargo bench --features avx-accel || true
