language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  - ARCH=x86_64
  - FEATURES=""
  - RUSTFLAGS="-C target-cpu=native"
matrix:
  include:
    - rust: stable
      env:
        - ARCH=i686
    - rust: beta
      env:
        - ARCH=i686
    - rust: nightly
      env:
        - ARCH=i686
    - rust: nightly
      env:
        - FEATURES="--features simd-accel"
    - rust: nightly
      env:
        - FEATURES="--features avx-accel"
addons:
  apt:
    packages:
      - gcc-multilib
script: |
  curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
  cargo test $FEATURES && cargo bench $FEATURES
