[package]
authors = ["Andre Bogus <bogusandre@gmail.de>", "Joshua Landau <joshua@landau.ws>"]
description = "count occurrences of a byte in a byte slice, fast"
name = "bytecount"
version = "0.1.4"
license = "Apache-2.0/MIT"
repository = "https://github.com/llogiq/bytecount"

[features]
avx-accel = ["simd-accel"]
simd-accel = ["simd"]

[dependencies]
simd = { version = "0.1.1", optional = true }

[dev-dependencies]
quickcheck = "0.3.1"
rand = "0.3.14"
